name: basic check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout node version
        run: node -v
        if: ${{ !startsWith(runner.os, 'v23.6.0') }}
        continue-on-error: true

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build
